services:
  mysql:
    image: mysql:8.4
    container_name: company-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root123!
      MYSQL_DATABASE: my_company_db
      MYSQL_USER: aydin
      MYSQL_PASSWORD: 123456!

    ports:
      - "3307:3306"

    volumes:
      - company_mysql_data:/var/lib/mysql

volumes:
  company_mysql_data: