spring.application.name=java-36-spring-boot-exception

server.port=9090

spring.datasource.url=jdbc:postgresql://localhost:5433/companydb
#spring.datasource.url=jdbc:postgresql://localhost:5433/companydb?currentSchema=development
spring.datasource.username=aydin
spring.datasource.password=123456!
spring.datasource.driver-class-name=org.postgresql.Driver
spring.data.jdbc.dialect=postgresql
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true