/*
 * This source file was generated by the Gradle 'init' task
 */
package com.aydindemir;

public class Library {
	
	public static void main(String[] args) {
		System.out.println("Gradle projesi çalıştı");
	}
    public boolean someLibraryMethod() {
        return true;
    }
}
